#!/usr/bin/ruby

# == Synopsis
#
#   A simple fact-keeping application.
#
# == Usage
#
#   Normal usage is as follows:
#
#     facts <action> <mode> <arg> [, <arg> [, <arg> ...]]
#
#   See the examples section for detailed usage on how to perform the various 
#   actions.
#
# == Options
#
# === Actions
#   -a, --daily      Get daily digest
#   -d, --destroy    Delete categories or facts
#   -e, --edit       Edit, for changing category names or fact content
#   -m, --move       Move, for moving categories and facts between categories
#   -n, --new        Create, for adding new categories and facts
#   -q, --query      Query, for querying categories and facts
#
# === Modes
#   -c, --category   Carries out an action on a category
#   -f, --fact       Carries out an action on a fact
#
# === Authentication
#   -U, --user       Sets the user to use for authentication
#   -P, --password   Sets the password to use for authentication
#   -s, --save-auth  Save the supplied credentials to ~/.factsrc
#
# === Miscellaneous
#   -b, --basic      Don't use any fancy terminal formatting for output
#   -h, --help       Displays help message
#   -p, --parent     Specifies that a new category should have a parent
#   -v, --verbose    Starts the program in verbose modew
#
# == Examples
#
# === Query
#   * Query for category information matching a specific pattern:
#
#       facts -qc ruby
#
#       facts -qfc apple (include facts in those categories)
#
#   * Query for facts that have content matching a specific pattern:
#
#       facts -qf "warren buffett"
#
# === New
#   * Create a top-level category:
#
#       facts -nc "Politics"
#
#   * Create a new child category by specifying a unique query for some parent 
#     category as the first argument (the -p switch lets the application know 
#     to expect a parent category first):
#
#       facts -npc "politics" "The Senate"
#
#   * Multiple new categories can be created at once:
#
#       facts -npc "politics" "Canadian Politics" "American Politics" ...
#
#   * Facts can be created in a similar manner:
#
#       facts -nf "politics" "Politicians are crooks"
#
#   * Categories or facts can be edited with $EDITOR by leaving off all "new" 
#     arguments:
#
#       facts -npc "politics"
#
# === Edit
#   * Edit a category name by specifying a search string followed by the new 
#     name:
#
#       facts -ec politics "Global Politics"
#
#   * Same for facts but with content:
#
#       facts -ef crooks "Politicians are lovely people"
#
#   * Leave off the second argument to edit the new name/content with $EDITOR: 
#
#       facts -ec politics
#       facts -ef crooks
#
# === Move
#   * Move one category to another (all arguments should be queries that will 
#     match only a single category):
#
#       facts -mc "dinosaurs" "zoology"
#
#   * Many categories can be moved at once, just keep in mind that the last 
#     argument is always the destination:
#
#       facts -mc "biology" "physics" ... "science"
#
#   * Facts are moved in the same fashion:
#
#       facts -mf "biology is the study of" biology
#
# === Destroy
#   * Destroy facts or categories by specifying a series of search strings 
#     (each of which matches exactly one fact or category):
#
#       facts -dc ruby
#       facts -df apple "steve jobs"
#
# == Author
#
#   Brandur Leach (brandur@mutelight.org)
#

require 'rubygems'
require 'bundler'
Bundler.setup

require 'lib/facts_client'
